import Link from "next/link";
import { useRouter } from "next/router";
import Head from "next/head";
import Button from "react-bootstrap/Button";
import { Container, Card } from "react-bootstrap";
import data from "./data.json";
import styles from "../styles/Home.module.css";

const about = () => {
  const route = useRouter();
  const id = route.query.id;
  const items = data.find((item) => item.id == id);
  console.log(items);
  return (
    <Container>
      <Head>
        <title>About Next JS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-center">
        <h1 className={styles.title}>
          Person
          <a target="_blank" href="">
            Details
          </a>
        </h1>
        {items && (
          <Card style={{ width: "18rem" }} className="m-auto mt-5">
            <Card.Img
              variant="top"
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5bT6Q5-caIiUkfDwUP_Dtbi0Y3TrCJ6DGOg&usqp=CAU"
            />
            <Card.Body>
              <Card.Title>{items.name}</Card.Title>
              <Card.Text>
                {items.email} <br /> {items.address}
              </Card.Text>
              <Link href="/">
                <Button variant="primary">Go Back</Button>
              </Link>
            </Card.Body>
          </Card>
        )}
        {!items && <h1>Loading.....</h1>}
      </main>
    </Container>
  );
};

export default about;
