import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Button from "react-bootstrap/Button";
import { Container, Row, Col, Card } from "react-bootstrap";
import Pagination from "react-bootstrap/Pagination";
import PageItem from "react-bootstrap/PageItem";
import data from "./data.json";
import { useState } from "react";

export default function Home() {
  const [currentPage, setCurrentPage] = useState(1);
  const [postsPerPage] = useState(5);

  const indexOfLastPost = currentPage * postsPerPage;
  const indexOfFirstPost = indexOfLastPost - postsPerPage;
  const currentPosts = data.slice(indexOfFirstPost, indexOfLastPost);

  const pageNumbers = [];

  for (let i = 1; i <= Math.ceil(data.length / postsPerPage); i++) {
    pageNumbers.push(i);
  }
  const paginate = (pageNumber) => setCurrentPage(pageNumber);
  const handlePrev = () => {
    if (currentPage > 1) {
      setCurrentPage(currentPage - 1);
    }
  };
  const handleNext = () => {
    if (currentPage < pageNumbers.length) {
      setCurrentPage(currentPage + 1);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>New Next Js app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello{" "}
          <a target="_blank" href="">
            There!
          </a>
        </h1>

        <p className={styles.description}>
          This Page Made with<code className={styles.code}>Next>JS</code>
        </p>

        <Container fluid>
          <Row className="justify-content-center justify-content-sm-center ">
            {currentPosts.map((item) => (
              <Col
                lg="4"
                md="6"
                sm="12"
                className="mt-3 justify-content-sm-center justify-content-md-center"
                key={item.id}
              >
                <Card style={{ width: "18rem" }}>
                  <Card.Img
                    variant="top"
                    src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5bT6Q5-caIiUkfDwUP_Dtbi0Y3TrCJ6DGOg&usqp=CAU"
                  />
                  <Card.Body>
                    <Card.Title>{item.name}</Card.Title>
                    <Card.Text>
                      {item.email} <br /> {item.address}
                    </Card.Text>
                    <Link href={`/${item.id}`}>
                      <Button variant="primary">See Details</Button>
                    </Link>
                  </Card.Body>
                </Card>
              </Col>
            ))}
          </Row>
          <Container className={styles.footer}>
            <Pagination className="m-auto">
              <Pagination.Prev onClick={handlePrev} />

              {pageNumbers.map((number) => (
                <Pagination.Item
                  active={currentPage === number}
                  onClick={() => paginate(number)}
                >
                  {number}
                </Pagination.Item>
              ))}

              <Pagination.Next onClick={handleNext} />
            </Pagination>
          </Container>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://imranchowdhury.me"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Imran
        </a>
      </footer>
    </div>
  );
}
